# ansible/roles/common/handlers/main.yml
---
- name: Restart chrony
  ansible.builtin.service:
    name: chrony
    state: restarted

- name: Restart ssh
  ansible.builtin.service:
    name: ssh
    state: restarted
