# ansible/roles/cli_host/handlers/main.yml
---
- name: Restart autofs
  ansible.builtin.service:
    name: autofs
    state: restarted

- name: Restart ssh
  ansible.builtin.service:
    name: ssh
    state: restarted
